repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        language_version: python3

-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
        args: [--safe]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
    -   id: mypy

-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.7.0
    hooks:
    -   id: setup-cfg-fmt
